### PR TITLE
Network out of band delete handle

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nnDarshan please review

i have setting ttl for network instead of deleting, here what drawback i seen is, global networks are stored under 
/networks/{subnet_id}/{node_id}/{interface_id} so ttl is set for interface level, suppose node does not have interface for a particular subnet then /networks/{subnet_id}/{node_id}/ is Empty so i am deleting Empty node_id dir, same logic for  /networks/{subnet_id}/   , problem is if ttl comes 0 then extra interfaces are deleted but these two directory deletion will happen coming node sync only. so upto that /networks/{subnet_id}/{node_id}/Empty directory will present.

is this cause any problem

**Comment by r0h4n** [comment]
Can you link to the tendrl issue?

**Comment by GowthamShanmugam** [comment]
@r0h4n this is not an issue for this

**Comment by GowthamShanmugam** [comment]
@r0h4n yes verified

**Pull request merged**
