### PR TITLE
Unit testcases for collectd gluster monitoring plugin

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@anmolbabu please review

**Comment by r0h4n** [comment]
The plugins have changed a lot https://github.com/Tendrl/node-agent/pull/599

Please update this PR

**Comment by GowthamShanmugam** [comment]
@r0h4n sure

**Comment by GowthamShanmugam** [comment]
@r0h4n @anmolbabu please review and merge this

**Comment by r0h4n** [comment]
Please update this after today's release

**Comment by GowthamShanmugam** [comment]
@r0h4n ok

**Comment by r0h4n** [comment]
Are these unit tests valid with latest master? Please check

**Comment by r0h4n** [comment]
Are these unit tests valid with latest master? Please check

**Pull request closed without merging**
