### PR TITLE
Installation descriptions removed from README.rst

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
tendrl-bug-id:Tendrl/node_agent#89
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nnDarshan , Please review

**Comment by r0h4n** [comment]
@TimothyAsir , Please respond to above comments

**Comment by TimothyAsirJeyasing** [comment]
Actually the installation instruction are repeated here so we removed it. Now the installation instruction are only available in https://github.com/Tendrl/node-agent/blob/master/doc/source/installation.rst

**Comment by r0h4n** [comment]
Let me know if this needs to be re-opened @TimothyAsir

**Pull request closed without merging**
