### PR TITLE
Fixing issue in disk sync for multipath device

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/node-agent#719

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat please review

**Comment by GowthamShanmugam** [comment]
Verified

**Comment by GowthamShanmugam** [comment]
@dahorak

**Comment by dahorak** [comment]
run tests

**Comment by dahorak** [comment]
@GowthamShanmugam I've verified, that there is no error `ERROR - node_sync disks sync failed: - KeyError` in `/var/log/messages`, should I check something else?

Tested on the same environment as for the initial issue https://github.com/Tendrl/node-agent/issues/719, with `tendrl-node-agent` from this PR (*tendrl-node-agent-1.6.1-9920180312T072318.461a6a0_fbac6fd.pr740*)

**Comment by GowthamShanmugam** [comment]
@dahorak thanks: +1:

**Pull request merged**
