### PR TITLE
WIP - Added flow for expand cluster

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
Verified the OSD node addition and works fine.
MON node addition still has some glitches. Need to correct and verify.

**Comment by shtripat** [comment]
There is a ceph BZ created https://bugzilla.redhat.com/show_bug.cgi?id=1446396 for MON addition issue.
Had tested the addition of OSD nodes earlier and worked as required.

We can merge the PR with a note that MON addition need to be re-looked once above BZ is fixed.

@Tendrl/tendrl-core comments?

**Comment by r0h4n** [comment]
The BZ is closed https://bugzilla.redhat.com/show_bug.cgi?id=1446396

The last comment on the BZ advises to use a newer version of the ceph-installer

**Comment by shtripat** [comment]
Yes @r0h4n will try to verify the scenario with latest ceph-installer once and update here.

**Comment by r0h4n** [comment]
these flows have to be in the root namespace which is "NS.tendrl" along with NS.tendrl.flows.CreateCluster" and "NS.tendrl.flows.ImportCluster"  and not in "NS.node_agent",  this PR should go in commons.

What we do need to refactor is , use the NS.integrations.{ceph, gluster} namespace (https://github.com/Tendrl/node-agent/tree/develop/tendrl/integrations) for defining ceph, gluster specific atoms instead of current ceph_help, gluster_help like files in commons

**Comment by shtripat** [comment]
>> these flows have to be in the root namespace which is "NS.tendrl" along with
>> NS.tendrl.flows.CreateCluster" and "NS.tendrl.flows.ImportCluster" and not in "NS.node_agent", this >> PR should go in commons.

>> What we do need to refactor is , use the NS.integrations.{ceph, gluster} namespace (https://github.com
>> /Tendrl/node-agent/tree/develop/tendrl/integrations) for defining ceph, gluster specific atoms instead >> of current ceph_help, gluster_help like files in commons

My understanding of flows is that any flow which is to be executed before existence of cluster, should be under `NS.tendrl` namespace and rest under either node-agent or integrations namespace.

The expand cluster is something which gets executed only once cluster is existing so ideal place is `NS.ceph` but due to restriction of ceph-installer here its been put under node-agent namespace.

Still I am open if you want it to be moved to commons.
Comments?

**Comment by r0h4n** [comment]
The generic flows need to be in NS.tendrl, and when we start sds specific actions those should be moved to NS.integrations.ceph,  my parent comment contains more details about how we refactor these generic flows

**Comment by shtripat** [comment]
Also the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1446396 is closed but with latest ceph-installer as well the mon addition fails. We are discussing with ceph team to resolve the same.

**Pull request closed without merging**
