### PR TITLE
Disable status related data pushes from collectd

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/node-agent#600
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat @shtripat Please review

To be verified

**Comment by shtripat** [comment]
@anmolbabu I understand these counts would now be calculated either in grafana or few ones from etcd. Correct?

**Comment by anmolbabu** [comment]
@shtripat They would be passed from monitoring-integration Cc: @rishubhjain

**Comment by shtripat** [comment]
@anmolbabu ok. Looks fine. Make sure after this removal still all the details are available to grafana.
@rishubhjain @GowthamShanmugam ^^^

**Comment by rishubhjain** [comment]
@anmolbabu So looking at the PR, it seems you have removed the following counters/data pushed by collectd:
1) Node (total, up, down)
2) Volume (total, up, dowm)
3) Volume status volume wise
4) Subvolume status for each volume
5) Brick status Node wise
6) Brick count
Is there anything I am missing?

**Comment by GowthamShanmugam** [comment]
LGTM, I feel these changes not affect  alerting dashboard

**Comment by anmolbabu** [comment]
@rishubhjain That's exactly the complete list that I have removed
>@anmolbabu So looking at the PR, it seems you have removed the following counters/data pushed by collectd:
Node (total, up, down)
Volume (total, up, dowm)
Volume status volume wise
Subvolume status for each volume
Brick status Node wise
Brick count (total, up, dowm) (node, cluster and volume level)
Brick status Volume wise
Is there anything I am missing?

**Comment by rishubhjain** [comment]
@r0h4n I have discussed this with @anmolbabu , all the things are in order, Please review and merge

**Comment by cloudbehl** [comment]
@anmolbabu @rishubhjain Looks good to me.

**Pull request merged**
