### PR TITLE
Removing spaces form disk id

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id : Tendrl/node-agent#538

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@brainfunked but key combination already have underscore is that ok.
device+"_"+vendor+"_"+serial_id

**Comment by brainfunked** [comment]
That'll need to be changed then. The character joining the words should be relatively obscure that it'll generally not be a part of a standard name. Colon maybe?

**Comment by GowthamShanmugam** [comment]
@r0h4n is colon is usable for key ?

**Comment by GowthamShanmugam** [comment]
@r0h4n need this patch for solve disk id problem which is faced by dahorak

**Comment by r0h4n** [comment]
@brainfunked @GowthamShanmugam please revisit the disk object to improve the naming scheme https://github.com/Tendrl/commons/blob/develop/tendrl/commons/objects/disk/__init__.py#L42

**Comment by GowthamShanmugam** [comment]
@r0h4n ok

**Pull request merged**
