### PR TITLE
Changed disk sync based on new disk structure

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: #463 
tendrl-spec-id: Tendrl/specifications#159
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @brainfunked @shtripat @nnDarshan @anivargi please review

**Comment by GowthamShanmugam** [comment]
Tested using VM and my local machine also

**Comment by GowthamShanmugam** [comment]
@brainfunked i have added disk name for physical disk and virtual disk as disk_id when by-id or (serial or model or vendor)  not found

**Comment by GowthamShanmugam** [comment]
@r0h4n verified with VM and physical disk

**Comment by anivargi** [comment]
PR For the disk changes. https://github.com/Tendrl/api/pull/192

**Pull request merged**
